apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  labels:
    app: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      serviceAccountName: authservice
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: server
        image: nandishasrn/authservice:958f3beddb138ec7a7b32563e46c95fc5b9f5866
        ports:
        - containerPort: 8081
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
        readinessProbe:
          initialDelaySeconds: 15
          httpGet:
            path: /health
            port: 8081
        livenessProbe:
          initialDelaySeconds: 15
          httpGet:
            path: /health
            port: 8081
        env:
        - name: PORT
          value: "8081"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authservice
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::508262720940:role/authservice-secret-role
